### ISSUE TITLE
Error when running raman-vasp.py

### ISSUE THREAD

**Issue by lzumuxijiao** [raman-sc/VASP#4]
Thank you very much for developing the raman-sc program for our convenience，I am having a problem running vasp_raman, an error occurred after running for a few minutes，
“Traceback （most recent call last）
 File "vasp_raman.py",line 291, in <module>
  eigval = eigvals [i]
IndexError: list index out of range"
the program running in CentOS 7.5 
I am not familiar with the python language, so I hope you guys will be able to answer this question.
Looking forward to your reply

**Comment by Crazerd** [comment]
I also met this problem, how to deal with it?

**Comment by Crazerd** [comment]
[sc52048@ln25%bscc-a phonopy-spectro]$ bash no_scheduler-phon-copy.sh 
Traceback (most recent call last):
  File "vasp_raman.py", line 268, in <module>
    eigvals = parse_freqdat(freqdat_fh, nat)
  File "vasp_raman.py", line 104, in parse_freqdat
    eigvals[i] = float(tmp[0])
IndexError: list index out of range

How to deal with this problem?
